apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hub-proxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hub-proxy-pod
    spec:
      containers:
      - name: hub-proxy-container
        image: yuvipanda/simplehub:v1.3
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 8000
            name: hub-proxy-port
---
apiVersion: v1
kind: Service
metadata:
  name: hub-proxy
spec:
  type: LoadBalancer
  selector:
    name: hub-proxy-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
