apiVersion: v1
kind: Service
metadata:
  name: hub
spec:
  type: LoadBalancer
  selector:
    name: hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hub
spec:
  replicas: 1
  selector:
    name: hub
  template:
    metadata:
      labels:
        name: hub
    spec:
      containers:
      - name: hub
        image: yuvipanda/simplehub:v1.1
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
          - containerPort: 8000
            name: hub-proxy
